"use client";
import { CheckCircle2, KeyRound, Loader2, X } from "lucide-react";
import { useState } from "react";
import { getSupabase } from "@/lib/supabase";
const cleanPin=(value:string)=>value.replace(/\D/g,"").slice(0,6);
export function PinChangeCard({isDemo}:{isDemo:boolean}) {
  const [pin,setPin]=useState(""); const [confirm,setConfirm]=useState(""); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  async function save(event:React.FormEvent){event.preventDefault();setError("");setMessage("");if(!/^\d{6}$/.test(pin)){setError("PIN must contain exactly 6 digits.");return}if(pin!==confirm){setError("PIN confirmation does not match.");return}setBusy(true);if(isDemo){await new Promise(r=>setTimeout(r,250));setMessage("Demo PIN changed for this session.");setPin("");setConfirm("");setBusy(false);return}const supabase=getSupabase();if(!supabase){setBusy(false);setError("Supabase is not configured.");return}const {error:updateError}=await supabase.auth.updateUser({password:pin});setBusy(false);if(updateError){setError(updateError.message);return}setMessage("Your new PIN is active.");setPin("");setConfirm("")}
  return <section className="pin-card"><div className="pin-card-copy"><div className="pin-icon"><KeyRound size={20}/></div><div><strong>Account PIN</strong><p>Use a private 6-digit PIN. Avoid keeping the shared initial PIN after your first login.</p></div></div><form className="pin-form" onSubmit={save}><label><span>New PIN</span><input type="password" inputMode="numeric" pattern="[0-9]{6}" value={pin} onChange={(e)=>setPin(cleanPin(e.target.value))} placeholder="••••••" required/></label><label><span>Confirm PIN</span><input type="password" inputMode="numeric" pattern="[0-9]{6}" value={confirm} onChange={(e)=>setConfirm(cleanPin(e.target.value))} placeholder="••••••" required/></label><button className="btn btn-dark" disabled={busy}>{busy?<Loader2 className="spin" size={16}/>:<KeyRound size={16}/>} Change PIN</button></form>{error&&<div className="form-error">{error}</div>}{message&&<div className="form-success"><CheckCircle2 size={15}/>{message}</div>}</section>
}
export function StudentPinResetModal({student,isDemo,onClose}:{student:any;isDemo:boolean;onClose:()=>void}) {
  const [pin,setPin]=useState("254912");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [done,setDone]=useState(false);
  async function reset(event:React.FormEvent){event.preventDefault();setError("");if(!/^\d{6}$/.test(pin)){setError("PIN must contain exactly 6 digits.");return}setBusy(true);if(isDemo){await new Promise(r=>setTimeout(r,250));setBusy(false);setDone(true);return}const supabase=getSupabase();if(!supabase){setBusy(false);setError("Supabase is not configured.");return}const {data,error:invokeError}=await supabase.functions.invoke("admin-create-student",{body:{action:"reset_pin",student_id:student.id,pin}});setBusy(false);if(invokeError||!data?.ok){let message=data?.error||invokeError?.message||"Could not reset PIN.";const context=(invokeError as {context?:Response}|null)?.context;if(context){try{const payload=await context.clone().json();if(payload?.error)message=payload.error}catch{}}setError(message);return}setDone(true)}
  return <div className="modal-backdrop" onMouseDown={onClose}><div className="pin-reset-modal" onMouseDown={(e)=>e.stopPropagation()}><div className="builder-head"><div><div className="eyebrow">ACCOUNT ACCESS</div><h2>Reset {student.name}&apos;s PIN</h2></div><button className="icon-btn" onClick={onClose}><X size={18}/></button></div>{done?<div className="pin-reset-success"><CheckCircle2 size={30}/><h3>PIN updated.</h3><p>Give the new PIN directly to {student.name}. Ask the student to change it from Profile after signing in.</p><div className="pin-display">{pin}</div><button className="btn btn-dark" onClick={onClose}>Done</button></div>:<form className="builder-form" onSubmit={reset}><div className="pin-reset-person"><div className="table-avatar">{student.name?.charAt(0)}</div><div><strong>{student.name}</strong><span>@{student.username||"student"}</span></div></div><label><span>New 6-digit PIN</span><input autoFocus type="text" inputMode="numeric" pattern="[0-9]{6}" minLength={6} maxLength={6} value={pin} onChange={(e)=>setPin(cleanPin(e.target.value))}/></label><div className="demo-hint">254912 is the default temporary PIN. For real student accounts, use a unique PIN when practical.</div>{error&&<div className="form-error">{error}</div>}<div className="builder-actions"><button type="button" className="btn btn-soft" onClick={onClose}>Cancel</button><button className="btn btn-primary" disabled={busy}>{busy?<Loader2 className="spin" size={16}/>:<KeyRound size={16}/>} Reset PIN</button></div></form>}</div></div>
}
